using Primer.Shared.Hosting;
using Primer.Shared.Presentation;

namespace Primer.Shared.Generation;

/// <summary>Raised when a file's managed region is opened but never closed.</summary>
internal sealed class MalformedRegionException(string relativePath) : PrimerException(new PrimerError(
    What: "The managed region is malformed",
    Subject: relativePath,
    NextAction: $"Restore the '{ManagedRegion.End}' marker, or delete the region and regenerate.",
    ExitCode: ExitCode.Configuration));

/// <summary>Raised when an existing file carries no managed region and force was not given.</summary>
internal sealed class UnmanagedFileException(string relativePath) : PrimerException(new PrimerError(
    What: "The file exists and was not generated by primer",
    Subject: relativePath,
    NextAction: "Pass --force to overwrite it. The prior content is backed up first.",
    ExitCode: ExitCode.Configuration));

/// <summary>
/// The delimited block whose content belongs to the generator. Content outside it belongs
/// to whoever wrote it, which is what lets a team add its own guidance to a generated file
/// without choosing between local edits and current output.
/// </summary>
internal static class ManagedRegion
{
    /// <summary>Opens the generated block.</summary>
    internal const string Begin = "<!-- primer:begin -->";

    /// <summary>Closes the generated block.</summary>
    internal const string End = "<!-- primer:end -->";

    /// <summary>Renders a body as a managed region, recording what produced it.</summary>
    internal static string Wrap(string body, string toolVersion, string contentHash) =>
        string.Join(
            '\n',
            Begin,
            $"<!-- generated by primer {toolVersion}; inputs {contentHash} -->",
            body.TrimEnd('\n'),
            End);

    /// <summary>
    /// Splits a file into the text before the region, and the text after it. A file with a
    /// begin marker and no end marker is malformed rather than treated as unmanaged: the
    /// safe reading of a half-open region is to refuse it.
    /// </summary>
    internal static bool TrySplit(
        string content,
        string relativePath,
        out string before,
        out string after)
    {
        before = string.Empty;
        after = string.Empty;

        var begin = content.IndexOf(Begin, StringComparison.Ordinal);
        var end = content.IndexOf(End, StringComparison.Ordinal);

        if (begin < 0 && end < 0)
        {
            return false;
        }

        if (begin < 0 || end < begin)
        {
            throw new MalformedRegionException(relativePath);
        }

        before = content[..begin];
        after = content[(end + End.Length)..];
        return true;
    }

    /// <summary>Whether a rendered body already carries the delimiters.</summary>
    internal static bool IsWrapped(string content) =>
        content.Contains(Begin, StringComparison.Ordinal) && content.Contains(End, StringComparison.Ordinal);

    /// <summary>Extracts just the delimited block from wrapped content.</summary>
    internal static string ExtractRegion(string wrapped)
    {
        var begin = wrapped.IndexOf(Begin, StringComparison.Ordinal);
        var end = wrapped.IndexOf(End, StringComparison.Ordinal);

        return begin < 0 || end < begin
            ? wrapped
            : wrapped[begin..(end + End.Length)];
    }
}
